### ISSUE TITLE
Radar Covid Doesn't work 

### ISSUE THREAD

**Issue by JacoboJesus** [RadarCOVID/radar-covid-ios#35] opened 2020-10-20 14:35 UTC
Hi,

While Contact Tracing works ok and show the positive contact, Radar Covid tell me 'Sin contactos de riesgo identificados'

--> IOS 14.01 / latest version of Radar Covid

![1](https://user-images.githubusercontent.com/73181784/96601318-2d84de00-12f2-11eb-981a-e02fb6adad19.jpg)
![2](https://user-images.githubusercontent.com/73181784/96601330-2fe73800-12f2-11eb-9691-a26f69d5c15f.jpg)
![3](https://user-images.githubusercontent.com/73181784/96601340-32e22880-12f2-11eb-9af6-743b81fe95bc.jpg)
![4](https://user-images.githubusercontent.com/73181784/96601345-34abec00-12f2-11eb-9602-57b33cb7fd2b.jpg)

**Comment by pvieito** [comment] 2020-10-20 15:15
Yes, this may be a serious issue, both the localization error and the UI update problem, have you tried force quitting and reopening the app?

// cc. @pantic79 @alopezh

**Comment by JacoboJesus** [comment] 2020-10-20 16:04
> Yes, this may be a serious issue, both the localization error and the UI update problem, have you tried force quitting and reopening the app?
> 
> // cc. @pantic79 @alopezh

Yes, kill and re-start and 'Sin contactos de riesgo identificados' perhaps if I reinstall it ...

**Comment by pvieito** [comment] 2020-10-20 16:09
@JacoboJesus yes, if you reinstall it, the app should re-download the infected keys, retry the exposure check, find the match and re-alert you.

**Comment by JacoboJesus** [comment] 2020-10-20 16:12
> @JacoboJesus yes, if you reinstall it, the app should re-download the infected keys, retry the exposure check, find the match and re-alert you.

Re-installed but still 'Sin contactos de riesgo ...' :(

**Comment by pvieito** [comment] 2020-10-20 16:15
Can you check in the Settings app if there are new exposure checks?

If not, try to force quit and reopen the app, I think doing that after reinstallation forces it to re-download the infected keys (if not it may do it later today).

**Comment by JacoboJesus** [comment] 2020-10-20 16:19
> Can you check in the Settings app if there are new exposure checks?
> 
> If not, try to force quit and reopen the app, I think doing that after reinstallation forces it to re-download the infected keys (if not it may do it later today).

When I reinstall it, new check and download was made but still the same info.

I wonder if it's a thing about thresholds, perhaps the contact with the positive was enough for Contact Tracing framework but not for RadarCovid

**Comment by pvieito** [comment] 2020-10-20 16:22
> When I reinstall it, new check and download was made but still the same info.

Great! 👍🏻

> I wonder if it's a thing about thresholds, perhaps the contact with the positive was enough for Contact Tracing framework but not for RadarCovid

Yes, let's wait for the Radar COVID team answer! But at least the the notification localization strings should be fixed and if the risk level is lower than the threshold no notification should appear 🤔

**Comment by pantic79** [comment] 2020-10-20 20:45
> I wonder if it's a thing about thresholds, perhaps the contact with the positive was enough for Contact Tracing framework but not for RadarCovid
That's right!. The framework reports a matching key,but you need to have a significant exposure to be reported as high exposure status. You could check the algorithm used for risk calculation and significant exposure [here](https://github.com/DP-3T/dp3t-sdk-android/blob/e4d71883ff0e25be3e59e4e0a8b445d73f35d346/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/internal/nearby/ExposureNotificationBroadcastReceiver.java#L54). As you commented, this has to do with the attenuation thresholds (proximity is inferred from signal attenuation) and the accumulated exposure time within these attenuation buckets.
Nevertheless, you get a quite a bit strange behaviour because the alert notification you get (the one with the localization issue) must be fired when the exposure is considered as a significant one and hence the APP status should reflect this.

We will try to reproduce this bug and then provid a fix for that.

Thanks for your support.

**Comment by pantic79** [comment] 2020-10-28 13:01
Just to give you an update. This issue has been reproduced and fixed. The fix will be available in the next release that will be uploaded to APP Store by tomorrow if nothing weird happens.

Thanks for your support.

**Comment by pvieito** [comment] 2020-10-28 13:26
@pantic79 Great! Any plan to push the changes to the public repo? I think it would be better for the project if the commits were published more frequently so the community could check them before going into a public release.

**Comment by pantic79** [comment] 2020-10-29 08:59
I agree. Our intention is to commit changes to develop branch at least once a week. Unfortunately it couldn't be possible for the moment.

Thanks.

**Comment by daronleaj** [comment] 2020-11-06 12:58
Fix Since version 1.1.1 
Both problems have been fixed:
1º The notification error has been corrected, collecting the backup that the user makes when consulting the lables service.
https://github.com/RadarCOVID/radar-covid-ios/commit/f1e86c718478c2c81a8330ca7ea52a5e048dbb29

2º Now on the start force the update of the status that DP3T returns.
https://github.com/RadarCOVID/radar-covid-ios/commit/2bae69373304e50362b66bd4e40782b20638779f

Thanks.

**Closed by daronleaj** 2020-11-06 12:58 UTC
